=head1 Quanto - MySQLProxy query aggregator

Easy aggregation of your query statistics.

    Tomas Doran &lt; t0m@state51.co.uk &gt;

=head1 Query comments

Change your code to emit a comment for each query.

    /* Filename@LINE_NO@subroutine */ <br>
        SELECT * <br>
        FROM giant_table <br>
        JOIN other_giant_table <br>
          WHERE unindexed_field = 'hahaha';<br>

You can see the comment when you C<SHOW PROCESSLIST>

Really handy!

=head1 Filename &amp; line + svn blame 

G<stab.jpg>

No use for lots of little queries in a loop though..

=head1 We generate by

G<upstack.png>

B<Example only> - apply to your language of choice.

=head1 And monkeypatch DBI

G<monkeypatch.png>

B<Example only> (although our technique is similar in ruby)

=head1 Quanto

Extension to MySQLProxy written in Lua.

Filters and aggregates your query comments.

Stores timing information, counts number of calls,
row counts returned etc.

Adds extra commands to the MySQL vocabulary to get query stats back.
CGI + JQuery to display in browser.

Solves the lots of queries in a loop problem.

B<NOT> perl specific.

=head1 Screen shot 1

G<quanto_shot1.png>

=head1 Screen shot 2

G<quanto_shot2.png>

=head1 Questions?

Code and presentation are on github:

    http://github.com/andym/Quanto

Patches welcome, especially solutions for generating query comments in your
language of choice, or a less crappy cgi.

Thanks!

=cut

